name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace
      
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: cbse-question-papers-debug
        path: app/build/outputs/apk/debug/*.apk
        retention-days: 30
        
    - name: Build Release APK (if signed)
      if: success()
      run: ./gradlew assembleRelease --stacktrace || echo "Release build failed - this is expected without signing configuration"
      continue-on-error: true
      
    - name: Upload Release APK as artifact (if exists)
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: cbse-question-papers-release
        path: app/build/outputs/apk/release/*.apk
        retention-days: 30
      continue-on-error: true
